[package]
name = "web3bounty-email-verify"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
airtable-flows = "0.1"
lambda-flows = "0.2"
serde_json = "1.0"
store-flows = "0.2"
sendgrid-flows = "0.1"
rand = "0.8"
